# version: 2.1
# orbs:
#   go: circleci/go@1.11.0
# jobs:
#   test-go:
#     parameters:
#       go-version:
#         type: string
#     executor:
#       name: go/default
#       tag: << parameters.go-version >>
#     steps:
#       - checkout
#       - go/load-cache
#       - go/mod-download
#       - go/save-cache
#       - run:
#           name: Run tests
#           command: make test_ci

# workflows:
#   test:
#     jobs:
#       - test-go:
#           matrix:
#             parameters:
#               go-version: ["1.20", "1.21", "1.22"]
