PROJECT_NAME: Medpoint
PROJECT_ID: okfiiamqfgxgutsyrdux
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_698525152e9c365334698fe11a088c819a654162
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZmlpYW1xZmd4Z3V0c3lyZHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMjY3MjAsImV4cCI6MjA1MTkwMjcyMH0.cloETRUCZ9TRgy5UqBCA8ToGR0hOXBDuU5nQSEcvQRU
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZmlpYW1xZmd4Z3V0c3lyZHV4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNjMyNjcyMSwiZXhwIjoyMDUxOTAyNzIxfQ.dXjG1WGY3sSJ3LS05Yfa7oqLojFZv2YwRpoNdK7Iksk

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://okfiiamqfgxgutsyrdux.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
